POST http://localhost:3300/feed/new
Content-Type: application/json

{
    "title":"The second post",
    "category":"General",
    "template":"100",
    "location":"DU",
    "content":"Glad its that level cool",
    "link":"http:....",
    "userId":"46",
    "username":"ping"
}

###

PATCH http://localhost:3300/feed/update
Content-Type: application/json

{
    "_id":"5eab0d96b1f0db1c32f65694",
    "_user_id":"45",
    "recogniser":"$2b$10$.H3.V40LyDTMx.Nnvljc7eZbOy2QanRQRe7IfVoeKA9pklV3z6Q2i",
    "likedUsers":[],
    "reportedUsers":[],
    "comments":[{"name":"annonymous","comment":"wow"},{"name":"annonymous","comment":"you're pretty amazing"}]
}

###

POST http://localhost:3300/feed/Global
Content-Type: application/json

{
    "pageNumber":1
}

###

POST http://localhost:3300/feed/posts/5eab0d96b1f0db1c32f65694
Content-Type: application/json

{
    "_user_id":"45"
}

###
