POST http://localhost:3300/feed/new
Content-Type: application/json

{
    "title":{
        "tag":"",
        "text":"Welcome",
        "className":""
    },
    "category":"Rumour",
    "content":[{
        "tags":"a",
        "text":"https://www.google.com",
        "className":"",
        "template":""
    },
    {
        "tags":"",
        "text":"To get help from google",
        "className":"",
        "template":""
    }],
    "location":"Jorhat Engineering College",
    "userId":"5ebbf98818f9562bb5b55f99",
    "username":"debashish",
    "name":"Debashish Gogoi"
}

###

PATCH http://localhost:3300/feed/update
Content-Type: application/json

{
    "_id":"5ebbfd6a3076732cca3e7fdd",
    "_user_id":"5ebbf98818f9562bb5b55f99",
    "recogniser":"$2b$10$NZ0OW67I/u5S..CyWmkBgeS9Pb2Y3pxDNYwzNyWYWd4lj1SvbAuma",
    "likedUsers":[],
    "reportedUsers":[],
    "comments":[{"name":"annonymous","comment":"wow"},{"name":"annonymous","comment":"you're pretty amazing"}]
}

###

POST http://localhost:3300/feed/Global
Content-Type: application/json

{
    "pageNumber":1
}

###

POST http://localhost:3300/feed/posts/5ebbfd6a3076732cca3e7fdd
Content-Type: application/json

{
    "_user_id":"5ebbfd6a3076732cca3e7fdd"
}

###
POST http://localhost:3300/feed/user/posts/debashish
Content-Type: application/json

{
    "_user_id":"5ebbfd6a3076732cca3e7fdd"
}

/////////////////////////////////////////////////

###
POST  https://my-fling.herokuapp.com/feed/user/posts/debashish
Content-Type: application/json

{
    "_user_id":"5ebbfd6a3076732cca3e7fdd"
}

###
POST https://my-fling.herokuapp.com/feed/new
Content-Type: application/json

{
    "title":{
        "tag":"",
        "text":"Welcome",
        "className":""
    },
    "category":"Rumour",
    "content":[{
        "tag":"a",
        "text":"https://www.google.com",
        "className":"",
        "template":""
    },
    {
        "tag":"",
        "text":"To get help  google",
        "className":"",
        "template":""
    }],
    "location":"Jorhat Engineering College",
    "userId":"5ebbf98818f9562bb5b55f99",
    "username":"debashish",
    "name":"Debashish Gogoi"
}

###

POST https://my-fling.herokuapp.com/feed/Global
Content-Type: application/json

{
    "pageNumber":1
}