POST http://localhost:3300/feed/user/new
Content-Type: application/json

{
    "username":"",
    "name":"",
    "password": "12345",
    "location": "Jorhat Engineering College"
}

###
POST http://localhost:3300/feed/user/del
Content-Type: application/json

{
    "username":"debashish"
}



