POST http://localhost:3300/feed/user/create
Content-Type: application/json

{
    "username":"Debashish Gogoi",
    "password": "12345",
    "location": "JEC"
}

###
GET http://localhost:3300/feed/user/

###
POST http://localhost:3300/feed/user/myposts/
Content-Type: application/json

{
    "_user_id":"47",
    "location":"DU"
}

